# Etapa de build com imagem completa
FROM node:20-slim AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Etapa final com nginx
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf